import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  AlertTriangle, ArrowLeft, Check, ChevronRight, ClipboardCheck, FileText,
  FolderOpen, LogOut, Pencil, Plus, RefreshCw, ShieldCheck, Trash2, Upload, UserRound,
} from "lucide-react";
import { criteriaGroups, criteriaLabels, criterionOutcomeLabels, assessmentTypes, recommendationGroups, outcomeColumns, reviewedCriteria, reportCriteria } from "./clinical";
import "./styles.css";

let csrfToken = "";
async function api(path, options = {}) {
  const headers = { ...(options.headers || {}) };
  if (!(options.body instanceof FormData) && options.body) headers["Content-Type"] = "application/json";
  if (csrfToken && !["GET", "HEAD"].includes(options.method || "GET")) headers["X-CSRF-Token"] = csrfToken;
  const response = await fetch(`/api${path}`, { credentials: "same-origin", ...options, headers });
  if (response.status === 204) return null;
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(data.message || data.error || "Request failed"), { data, status: response.status });
  return data;
}

function Notice({ tone = "info", children }) { return <div className={`notice ${tone}`}><AlertTriangle size={17}/><span>{children}</span></div>; }
function Button({ variant = "primary", icon: Icon, children, ...props }) {
  return <button className={`button ${variant}`} {...props}>{Icon && <Icon size={16}/>} {children}</button>;
}

function Login({ onLogin }) {
  const [form, setForm] = useState({ username: "", password: "" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function submit(e) {
    e.preventDefault(); setBusy(true); setError("");
    try { const result = await api("/auth/login", { method: "POST", body: JSON.stringify(form) }); csrfToken = result.csrf_token; onLogin(result.user); }
    catch (err) { setError(err.data?.error === "account_locked" ? "Account temporarily locked. Try again later." : "The username or password was not recognised."); }
    finally { setBusy(false); }
  }
  return <main className="login-shell">
    <section className="login-brand"><div className="brand-mark">C</div><p>CLINICAL REPORT WORKSPACE</p><h1>Clear evidence.<br/>Clinician judgement.</h1><p className="lede">A focused workspace for preparing adult and adolescent ADHD assessment reports.</p></section>
    <section className="login-panel"><form className="login-card" onSubmit={submit}>
      <div className="eyebrow">SECURE CLINICIAN ACCESS</div><h2>Welcome back</h2><p>Sign in with the account created by your administrator.</p>
      {error && <Notice tone="danger">{error}</Notice>}
      <label>Username<input autoComplete="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required/></label>
      <label>Password<input type="password" autoComplete="current-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>
      <Button disabled={busy}>{busy ? "Signing in…" : "Sign in"}</Button>
      <p className="security-note"><ShieldCheck size={15}/>Protected health information. Authorised clinicians only.</p>
    </form></section>
  </main>;
}

function Shell({ user, children, onLogout }) {
  return <div className="app-shell"><header className="topbar"><div className="wordmark"><span>C</span><div><strong>Clarity</strong><small>ADHD report workspace</small></div></div><div className="user-menu"><UserRound size={17}/><span>{user.full_name}</span><button onClick={onLogout} title="Sign out"><LogOut size={17}/></button></div></header>{children}</div>;
}

function CaseList({ onOpen }) {
  const [cases, setCases] = useState([]); const [showNew, setShowNew] = useState(false); const [error, setError] = useState("");
  async function load(){ try{ setCases(await api("/cases")); }catch(e){setError(e.message)} }
  useEffect(()=>{load()},[]);
  return <main className="page"><div className="page-head"><div><div className="eyebrow">CLINICIAN DASHBOARD</div><h1>Assessment cases</h1><p>Prepare, review and approve evidence-grounded reports.</p></div><Button icon={Plus} onClick={()=>setShowNew(true)}>New case</Button></div>
    {error && <Notice tone="danger">{error}</Notice>}
    <div className="case-grid">{cases.map(item=><button key={item.id} className="case-card" onClick={()=>onOpen(item.id)}><div className="case-icon"><FolderOpen/></div><div><div className="case-top"><span className={`pill ${item.status}`}>{item.status.replaceAll("-"," ")}</span><small>{item.cohort}</small></div><h3>{item.patient_initials}</h3><p>{item.referral_question || "Referral question not yet entered"}</p><small>Updated {new Date(item.updated_at).toLocaleDateString()}</small></div><ChevronRight/></button>)}</div>
    {!cases.length && <div className="empty"><FileText size={36}/><h3>No assessment cases yet</h3><p>Create the first case to begin organising evidence.</p></div>}
    {showNew && <NewCase onClose={()=>setShowNew(false)} onCreated={id=>onOpen(id)}/>}</main>;
}

function NewCase({ onClose, onCreated }) {
  const [form,setForm]=useState({cohort:"adult",patient_initials:"",referral_question:"",cloud_consent:false}); const [error,setError]=useState("");
  async function submit(e){e.preventDefault();try{const value=await api("/cases",{method:"POST",body:JSON.stringify(form)});onCreated(value.id)}catch(err){setError(err.message)}}
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="eyebrow">NEW ASSESSMENT</div><h2>Create a case</h2>{error&&<Notice tone="danger">{error}</Notice>}
    <label>Patient initials<input value={form.patient_initials} onChange={e=>setForm({...form,patient_initials:e.target.value})} maxLength={12} required/></label>
    <label>Cohort<select value={form.cohort} onChange={e=>setForm({...form,cohort:e.target.value})}><option value="adult">Adult</option><option value="adolescent">Adolescent</option></select></label>
    <label>Referral question<textarea rows="3" value={form.referral_question} onChange={e=>setForm({...form,referral_question:e.target.value})}/></label>
    <label className="check"><input type="checkbox" checked={form.cloud_consent} onChange={e=>setForm({...form,cloud_consent:e.target.checked})}/><span>The patient privacy notice permits AI processing within Australia.</span></label>
    <div className="actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button>Create case</Button></div></form></div>;
}

function CaseWorkspace({ caseId, onBack }) {
  const [data,setData]=useState(null), [tab,setTab]=useState("overview"), [error,setError]=useState("");
  async function load(){try{setData(await api(`/cases/${caseId}`));setError("")}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[caseId]);
  useEffect(()=>{if(!data?.jobs?.some(j=>["queued","running"].includes(j.status)))return;const id=setInterval(load,2500);return()=>clearInterval(id)},[data?.jobs]);
  if(!data)return <main className="page"><Button variant="ghost" icon={ArrowLeft} onClick={onBack}>Cases</Button>{error?<Notice tone="danger">{error}</Notice>:<p>Loading case…</p>}</main>;
  const tabs=[['overview','Overview'],['sources','Sources'],['evidence',`Evidence (${data.evidence.length})`],['criteria','Criteria'],['report','Report']];
  return <main className="workspace"><aside className="case-nav"><Button variant="ghost" icon={ArrowLeft} onClick={onBack}>All cases</Button><div className="case-identity"><span>{data.case.cohort}</span><h2>{data.case.patient_initials}</h2><p>{data.case.referral_question||"No referral question"}</p></div><nav>{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}<ChevronRight size={15}/></button>)}</nav><div className="case-status"><small>REPORT STATUS</small><strong>{data.case.status.replaceAll("-"," ")}</strong></div></aside>
    <section className="workspace-main">{error&&<Notice tone="danger">{error}</Notice>}{tab==='overview'&&<Overview data={data} reload={load}/>} {tab==='sources'&&<Sources data={data} reload={load}/>} {tab==='evidence'&&<Evidence data={data} reload={load}/>} {tab==='criteria'&&<Criteria data={data} reload={load}/>} {tab==='report'&&<Report data={data} reload={load}/>}</section></main>;
}

function Overview({data,reload}) {
  const c=data.case; const [form,setForm]=useState({demographics:{...(c.demographics||{})},referral_question:c.referral_question,final_diagnostic_conclusion:c.final_diagnostic_conclusion,cloud_consent:c.cloud_consent,assessment_dates:(c.assessment_dates||[]).join(', '),instruments:(c.instruments||[]).join(', ')});
  async function save(){await api(`/cases/${c.id}`,{method:"PATCH",body:JSON.stringify({...form,assessment_dates:form.assessment_dates.split(',').map(x=>x.trim()).filter(Boolean),instruments:form.instruments.split(',').map(x=>x.trim()).filter(Boolean)})});reload()}
  return <div><PageTitle eyebrow="CASE INTAKE" title="Overview" text="Clinical context and completion safeguards."/><div className="stats"><Stat value={data.sources.length} label="Sources"/><Stat value={data.evidence.filter(e=>e.verified).length} label="Verified evidence"/><Stat value={reviewedCriteria(data.criteria,c.cohort)+"/18"} label="Criteria reviewed"/></div>
    {!!data.warnings.length&&<section className="panel"><h3>Clinical completeness</h3>{data.warnings.map((w,i)=><Notice key={i}>{w}</Notice>)}</section>}
    <section className="panel form-grid">{[['age','Age at assessment'],['gender','Gender as reported'],['birthplace','Birthplace'],['living_arrangement','Current living arrangements'],['reported_by','Demographic details reported by']].map(([field,label])=><label key={field}>{label}<input value={form.demographics[field]??''} onChange={e=>setForm({...form,demographics:{...form.demographics,[field]:e.target.value}})}/></label>)}<label className="wide">Referral question<textarea rows="4" value={form.referral_question} onChange={e=>setForm({...form,referral_question:e.target.value})}/></label><label>Assessment dates<input value={form.assessment_dates} onChange={e=>setForm({...form,assessment_dates:e.target.value})} placeholder="2026-08-01, 2026-08-03"/></label><label>Instruments<input value={form.instruments} onChange={e=>setForm({...form,instruments:e.target.value})} placeholder="DIVA-5, ASRS"/></label><label className="wide">Clinician diagnostic conclusion<textarea rows="5" value={form.final_diagnostic_conclusion} onChange={e=>setForm({...form,final_diagnostic_conclusion:e.target.value})} placeholder="Entered by the approving clinician; the model cannot decide this."/></label><label className="check wide"><input type="checkbox" checked={form.cloud_consent} onChange={e=>setForm({...form,cloud_consent:e.target.checked})}/><span>Cloud-processing consent acknowledged</span></label><div className="wide actions"><Button onClick={save}>Save overview</Button></div></section><InstrumentPanel data={data} reload={reload}/></div>;
}
function InstrumentPanel({data,reload}) {
  const empty={instrument:'',version:'',respondent:'',interpretation:'',assessment_type:'questionnaire',scores_text:'{}',verified:false};
  const [form,setForm]=useState(empty),[editing,setEditing]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function save(e){
    e.preventDefault();setError('');setBusy(true);
    try {
      const scores=JSON.parse(form.scores_text);
      if(!scores||Array.isArray(scores)||typeof scores!=='object')throw new Error('Scored results must be a JSON object.');
      await api(`/cases/${data.case.id}/instruments${editing?`/${editing}`:''}`,{method:editing?'PATCH':'POST',body:JSON.stringify({...form,scores})});
      setForm(empty);setEditing(null);await reload();
    } catch(err){setError(err instanceof SyntaxError?'Enter valid JSON for already-scored results.':err.message)}finally{setBusy(false)}
  }
  function edit(item){setEditing(item.id);setForm({...item,scores_text:JSON.stringify(item.scores,null,2),verified:false});setError('')}
  return <section className="panel"><h3>Scored instrument summaries</h3><p className="muted">Enter only authorised, already-scored results and interpretations. Classify questionnaires and cognitive assessments separately.</p>{error&&<Notice tone="danger">{error}</Notice>}<div className="list">{data.instruments.map(x=><div className="list-row" key={x.id}><div className="file-badge"><ClipboardCheck/></div><div><strong>{x.instrument} {x.version}</strong><p>{x.respondent||'Respondent not set'} · {assessmentTypes[x.assessment_type||'other']} · {x.interpretation||'No clinician interpretation'}</p></div><span className={`pill ${x.verified?'verified':''}`}>{x.verified?'verified':'unverified'}</span><Button variant="ghost" onClick={()=>edit(x)}>Edit</Button></div>)}</div>
    <form className="form-grid instrument-form" onSubmit={save}>
      <label>Instrument<input required value={form.instrument} onChange={e=>setForm({...form,instrument:e.target.value})}/></label>
      <label>Assessment type<select value={form.assessment_type} onChange={e=>setForm({...form,assessment_type:e.target.value})}>{Object.entries(assessmentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label>Version<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label>
      <label>Respondent<input value={form.respondent} onChange={e=>setForm({...form,respondent:e.target.value})}/></label>
      <label className="wide">Already-scored results (JSON)<textarea rows="3" value={form.scores_text} onChange={e=>setForm({...form,scores_text:e.target.value})}/></label>
      <label className="wide">Clinician interpretation<textarea rows="3" value={form.interpretation} onChange={e=>setForm({...form,interpretation:e.target.value})}/></label>
      <label className="check"><input type="checkbox" checked={form.verified} onChange={e=>setForm({...form,verified:e.target.checked})}/><span>Scores, interpretation and classification independently verified</span></label>
      <div className="wide actions"><Button variant="secondary" disabled={busy}>{editing?'Save summary':'Add summary'}</Button>{editing&&<Button type="button" variant="ghost" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel edit</Button>}</div>
    </form></section>;
}

function Stat({value,label}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
function PageTitle({eyebrow,title,text,action}){return <div className="section-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action}</div>}

function Sources({data,reload}) {
  const [file,setFile]=useState(null),[meta,setMeta]=useState({source_type:"transcript",reporter:"",setting:"unspecified",instrument:"",assessment_type:"other"}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[deleting,setDeleting]=useState(null),[editing,setEditing]=useState(null),[confirmingUpload,setConfirmingUpload]=useState(false);
  function prepareUpload(e){e.preventDefault();if(file)setConfirmingUpload(true)}
  async function upload(){if(!file)return;setBusy(true);setError("");const body=new FormData();body.append('file',file);Object.entries(meta).forEach(([k,v])=>body.append(k,v));try{await api(`/cases/${data.case.id}/sources`,{method:'POST',body});setFile(null);setConfirmingUpload(false);await reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function remove(source){setBusy(true);setError("");try{await api(`/cases/${data.case.id}/sources/${source.id}`,{method:'DELETE'});setDeleting(null);await reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function rename(source,patch){setBusy(true);setError("");try{await api(`/cases/${data.case.id}/sources/${source.id}`,{method:'PATCH',body:JSON.stringify(patch)});setEditing(null);await reload()}catch(err){setError(err.message);throw err}finally{setBusy(false)}}
  return <div><PageTitle eyebrow="SOURCE MATERIAL" title="Documents" text="TXT, DOCX and text-based PDFs. Maximum 25 MB each."/>{error&&<Notice tone="danger">{error}</Notice>}<form className="upload-panel" onSubmit={prepareUpload}><Upload size={28}/><div><h3>Add source material</h3><p>Raw proprietary test responses and macro-enabled files are not accepted.</p></div><input type="file" accept=".txt,.docx,.pdf" onChange={e=>setFile(e.target.files[0])}/><select value={meta.source_type} onChange={e=>setMeta({...meta,source_type:e.target.value})}><option value="transcript">Session transcript</option><option value="questionnaire">Questionnaire narrative</option><option value="collateral">Collateral report</option><option value="instrument_export">Scored instrument export</option></select><select aria-label="Source assessment type" value={meta.assessment_type} onChange={e=>setMeta({...meta,assessment_type:e.target.value})}>{Object.entries(assessmentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input placeholder="Instrument (e.g. DIVA-5)" value={meta.instrument} onChange={e=>setMeta({...meta,instrument:e.target.value})}/><input placeholder="Reporter (e.g. parent)" value={meta.reporter} onChange={e=>setMeta({...meta,reporter:e.target.value})}/><select value={meta.setting} onChange={e=>setMeta({...meta,setting:e.target.value})}>{['unspecified','home','school','work','social','clinical','other'].map(x=><option key={x}>{x}</option>)}</select><Button disabled={!file||busy}>{busy?'Uploading…':'Upload & extract'}</Button></form>
  <div className="list">{data.sources.map(s=><div className="list-row" key={s.id}><div className="file-badge"><FileText/></div><div><div className="source-name"><strong>{s.original_filename}</strong><button className="icon-button" onClick={()=>setEditing(s)} title={`Rename ${s.original_filename}`} aria-label={`Rename ${s.original_filename}`} disabled={busy}><Pencil size={14}/></button></div><p>{s.source_type} · {s.reporter||'Reporter not set'} · {s.setting||'Setting not set'}</p></div><div className="source-actions"><span className={`pill ${s.extraction_status}`}>{s.extraction_status}</span><button className="icon-button danger-button" onClick={()=>setDeleting(s)} title={`Delete ${s.original_filename}`} aria-label={`Delete ${s.original_filename}`} disabled={busy}><Trash2 size={15}/></button></div></div>)}</div>{confirmingUpload&&<UploadConfirmation fileName={file?.name} busy={busy} onCancel={()=>setConfirmingUpload(false)} onConfirm={upload}/>} {editing&&<RenameSourceDialog source={editing} busy={busy} onCancel={()=>setEditing(null)} onSave={name=>rename(editing,name)}/>} {deleting&&<DeleteSourceDialog source={deleting} evidenceCount={data.evidence.filter(e=>e.source_id===deleting.id).length} busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>remove(deleting)}/>}</div>;
}

function UploadConfirmation({fileName,busy,onCancel,onConfirm}) {
  const [acknowledged,setAcknowledged]=useState(false);
  return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="upload-confirmation-title"><div className="eyebrow">AI ANALYSIS</div><h2 id="upload-confirmation-title">Confirm document upload</h2><p className="modal-copy"><strong>{fileName}</strong> will be sent to the configured AI service for evidence extraction. Before continuing, remove or replace direct personal identifiers, including names, dates of birth, addresses, contact details, record numbers and other identifying information.</p><label className="check"><input type="checkbox" checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)}/><span>I confirm that this document has been de-identified for AI analysis.</span></label><div className="actions"><Button type="button" variant="ghost" onClick={onCancel} disabled={busy}>Cancel</Button><Button type="button" onClick={onConfirm} disabled={!acknowledged||busy}>{busy?'Uploading…':'Confirm & upload'}</Button></div></section></div>;
}

function RenameSourceDialog({source,busy,onCancel,onSave}) {
  const [filename,setFilename]=useState(source.original_filename),[assessmentType,setAssessmentType]=useState(source.assessment_type||"other"),[instrument,setInstrument]=useState(source.instrument||""),[error,setError]=useState('');
  async function submit(e){e.preventDefault();setError('');try{await onSave({original_filename:filename.trim(),assessment_type:assessmentType,instrument})}catch(err){setError(err.message)}}
  return <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={submit} aria-labelledby="rename-source-title"><div className="eyebrow">SOURCE DOCUMENT</div><h2 id="rename-source-title">Edit source details</h2><p className="modal-copy">The file extension is fixed to preserve extraction compatibility.</p>{error&&<Notice tone="danger">{error}</Notice>}<label>File name<input value={filename} onChange={e=>setFilename(e.target.value)} required maxLength="255"/></label><label>Assessment type<select value={assessmentType} onChange={e=>setAssessmentType(e.target.value)}>{Object.entries(assessmentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Instrument<input value={instrument} onChange={e=>setInstrument(e.target.value)}/></label><p>Changing source metadata does not reclassify verified passages. Review individual evidence cards for mixed documents.</p><div className="actions"><Button type="button" variant="ghost" onClick={onCancel} disabled={busy}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save details'}</Button></div></form></div>;
}

function DeleteSourceDialog({source,evidenceCount,busy,onCancel,onConfirm}) {
  return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="delete-source-title"><div className="eyebrow">PERMANENT REMOVAL</div><h2 id="delete-source-title">Delete source document?</h2><p className="modal-copy"><strong>{source.original_filename}</strong> will be permanently deleted, along with {evidenceCount} extracted evidence {evidenceCount===1?'item':'items'}. This cannot be undone.</p><div className="actions"><Button type="button" variant="ghost" onClick={onCancel} disabled={busy}>Cancel</Button><Button type="button" variant="danger" icon={Trash2} onClick={onConfirm} disabled={busy}>{busy?'Deleting…':'Delete document'}</Button></div></section></div>;
}

function Evidence({data,reload}) {
  const [domainFilter,setDomainFilter]=useState('all'),[sourceFilter,setSourceFilter]=useState('all'),[error,setError]=useState(''),[editing,setEditing]=useState(null);
  const domainOptions=data.evidence_domains||[]; const items=data.evidence.filter(e=>(domainFilter==='all'||e.domain===domainFilter)&&(sourceFilter==='all'||e.source_id===sourceFilter));
  async function update(item,patch){setError('');try{await api(`/cases/${data.case.id}/evidence/${item.id}`,{method:'PATCH',body:JSON.stringify(patch)});await reload();return true}catch(err){setError(err.message);return false}}
  return <div><PageTitle eyebrow="EVIDENCE LEDGER" title="Verify extracted evidence" text="Review and, where needed, correct extracted evidence before verification."/>{error&&<Notice tone="danger">{error}</Notice>}<div className="toolbar"><div className="evidence-filters"><select aria-label="Filter evidence by source document" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="all">All source documents</option>{data.sources.map(source=><option key={source.id} value={source.id}>{source.original_filename}</option>)}</select><select aria-label="Filter evidence by domain" value={domainFilter} onChange={e=>setDomainFilter(e.target.value)}><option value="all">All domains</option>{domainOptions.map(d=><option key={d.value} value={d.value}>{d.label}</option>)}</select></div><span>{items.filter(i=>i.verified).length} verified in this view</span></div><div className="evidence-list">{items.map(item=><article className={`evidence-card ${item.verified?'verified':''}`} key={item.id}><div className="evidence-meta"><label className="evidence-domain">Domain<select aria-label="Evidence domain" value={item.domain} title={domainOptions.find(d=>d.value===item.domain)?.description} onChange={e=>update(item,{domain:e.target.value})}>{domainOptions.map(d=><option key={d.value} value={d.value}>{d.label}</option>)}</select></label><button className="icon-button" onClick={()=>setEditing(item)} title="Edit evidence" aria-label="Edit evidence"><Pencil size={15}/></button></div><small className="evidence-reporter">{item.reporter||'Unknown reporter'} · {item.setting} · {assessmentTypes[item.assessment_type||'other']} · {item.timeframe||'unspecified'} {(item.criterion_ids||[]).join(', ')}</small><p>“{item.supporting_text}”</p><div className="evidence-foot"><small>{item.source_location} · confidence {Math.round(item.confidence*100)}%</small><label className="check"><input type="checkbox" checked={item.verified} onChange={e=>update(item,{verified:e.target.checked})}/><span>{item.verified?'Verified':'Verify'}</span></label></div></article>)}</div>{!items.length&&<div className="empty"><ClipboardCheck/><h3>No extracted evidence in this view</h3><p>Adjust the source document or domain filters, or upload and process a source document.</p></div>}{editing&&<EvidenceEditor item={editing} domainOptions={domainOptions} onClose={()=>setEditing(null)} onSave={async patch=>{if(await update(editing,patch))setEditing(null);else throw new Error('Unable to save changes.')}}/>}</div>;
}

function EvidenceEditor({item,domainOptions,onClose,onSave}) {
  const [form,setForm]=useState({assessment_type:item.assessment_type||"other",criterion_ids:item.criterion_ids||[],timeframe:item.timeframe||"unspecified",domain:item.domain,supporting_text:item.supporting_text,reporter:item.reporter,setting:item.setting,source_location:item.source_location,confidence:item.confidence,contradiction_status:item.contradiction_status}); const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setError('');const confidence=Number(form.confidence);if(!form.supporting_text.trim()){setError('Evidence text is required.');return}if(!Number.isFinite(confidence)||confidence<0||confidence>1){setError('Confidence must be between 0 and 1.');return}setBusy(true);try{await onSave({...form,supporting_text:form.supporting_text.trim(),confidence})}catch(err){setError(err.message);setBusy(false)}}
  return <div className="modal-backdrop" role="presentation"><form className="modal evidence-editor" onSubmit={submit}><div className="eyebrow">EVIDENCE CARD</div><h2>Edit evidence</h2><p>Keep the extracted wording and provenance accurate before verifying this item.</p>{error&&<Notice tone="danger">{error}</Notice>}<label>Domain<select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}>{domainOptions.map(d=><option key={d.value} value={d.value}>{d.label}</option>)}</select></label><label>Assessment provenance<select value={form.assessment_type} onChange={e=>setForm({...form,assessment_type:e.target.value})}>{Object.entries(assessmentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{form.assessment_type==='diva'&&<><label>Timeframe<select value={form.timeframe} onChange={e=>setForm({...form,timeframe:e.target.value})}>{['unspecified','adulthood','childhood','adolescence'].map(value=><option key={value}>{value}</option>)}</select></label><fieldset><legend>Criteria discussed (not outcome decisions)</legend><div className="criterion-tags">{Object.entries(criteriaLabels).map(([id,label])=><label className="check" key={id}><input type="checkbox" checked={form.criterion_ids.includes(id)} onChange={e=>setForm({...form,criterion_ids:e.target.checked?[...form.criterion_ids,id]:form.criterion_ids.filter(x=>x!==id)})}/>{id} {label}</label>)}</div></fieldset></>}<label>Supporting evidence<textarea rows="5" maxLength="800" value={form.supporting_text} onChange={e=>setForm({...form,supporting_text:e.target.value})} required/></label><div className="form-grid"><label>Reporter<input value={form.reporter} onChange={e=>setForm({...form,reporter:e.target.value})}/></label><label>Setting<input value={form.setting} onChange={e=>setForm({...form,setting:e.target.value})}/></label><label>Source location<input value={form.source_location} onChange={e=>setForm({...form,source_location:e.target.value})}/></label><label>Confidence (0–1)<input type="number" min="0" max="1" step="0.01" value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}/></label></div><label>Contradiction status<select value={form.contradiction_status} onChange={e=>setForm({...form,contradiction_status:e.target.value})}><option value="none">None identified</option><option value="possible">Possible contradiction</option><option value="confirmed">Confirmed contradiction</option></select></label><div className="actions"><Button type="button" variant="ghost" onClick={onClose} disabled={busy}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save changes'}</Button></div></form></div>;
}

function Criteria({data,reload}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const columns=outcomeColumns(data.case.cohort);
  async function change(item,field,outcome){setBusy(true);setError("");try{await api(`/cases/${data.case.id}/criteria/${item.criterion_id}`,{method:'PUT',body:JSON.stringify({[field]:outcome})});await reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function setAllMet(field){setBusy(true);setError("");try{await Promise.all(data.criteria.map(item=>api(`/cases/${data.case.id}/criteria/${item.criterion_id}`,{method:'PUT',body:JSON.stringify({[field]:'met'})})));await reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div><PageTitle eyebrow="CLINICIAN DECISION" title="Diagnostic criteria" text="The clinician sets each criterion outcome. Generate a new draft after changing decisions." action={<div className="actions">{columns.map(([field,label])=><Button key={field} variant="secondary" onClick={()=>setAllMet(field)} disabled={busy||data.criteria.every(c=>c[field]==='met')}>Set {label.toLowerCase()} to Met</Button>)}</div>}/>{error&&<Notice tone="danger">{error}</Notice>}<Notice>Rating scales are supporting evidence and cannot independently establish a diagnosis.</Notice><div className="criteria-grid">{data.criteria.map(item=><div className="criterion" key={item.criterion_id}><div><strong>{item.criterion_id}</strong><span>{criteriaLabels[item.criterion_id]}</span>{data.case.cohort==='adult'&&item.clinician_outcome!=='unreviewed'&&<small>Legacy outcome (period unspecified): {criterionOutcomeLabels[item.clinician_outcome]}</small>}</div><div className="criterion-outcomes">{columns.map(([field,label])=><label key={field}>{label}<select className={item[field]||'unreviewed'} value={item[field]||'unreviewed'} disabled={busy} onChange={e=>change(item,field,e.target.value)}>{Object.entries(criterionOutcomeLabels).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>)}</div></div>)}</div></div>;
}

function CriteriaReportTable({criteria,cohort}) {
  const byId=new Map(criteria.map(item=>[item.criterion_id,item]));
  const columns=outcomeColumns(cohort);
  return <div className={`criteria-report ${cohort}`}>{criteriaGroups.map(group=><table key={group.prefix}><thead><tr><th>{group.title}</th>{columns.map(([field,label])=><th key={field}>{label}</th>)}</tr></thead><tbody>{Object.entries(criteriaLabels).filter(([id])=>id.startsWith(group.prefix)).map(([id,label],index)=><tr key={id}><td><span>{String.fromCharCode(97+index)}.</span>{label}</td>{columns.map(([field])=>{const outcome=byId.get(id)?.[field]||'unreviewed';return <td key={field} className={outcome}>{outcome==='met'&&<Check size={15}/>} {criterionOutcomeLabels[outcome]}</td>})}</tr>)}</tbody></table>)}</div>;
}

function Report({data,reload}) {
  const draft=data.drafts[0]; const draftJobs=data.jobs.filter(j=>j.job_type==='generate_draft'); const activeJob=draftJobs.find(j=>['queued','running'].includes(j.status)); const latestFailedJob=draftJobs.find(j=>j.status==='failed'); const [selectedEvidence,setSelectedEvidence]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function generate(){setBusy(true);try{await api(`/cases/${data.case.id}/drafts`,{method:'POST',body:'{}'});await reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function save(patch){setBusy(true);try{await api(`/cases/${data.case.id}/drafts/${draft.id}`,{method:'PATCH',body:JSON.stringify(patch)});await reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function approve(){setBusy(true);try{await api(`/cases/${data.case.id}/drafts/${draft.id}/approve`,{method:'POST',body:'{}'});await reload()}catch(e){setError(e.data?.requirements?.join(' ')||e.message)}finally{setBusy(false)}}
  function editParagraph(si,pi,text){const sections=structuredClone(draft.sections);sections[si].paragraphs[pi].text=text;sections[si].paragraphs[pi].quotations=(sections[si].paragraphs[pi].quotations||[]).filter(q=>text.includes(q.text));save({sections})}
  if(!draft)return <div><PageTitle eyebrow="REPORT DRAFT" title="Generate report" text="Drafting uses verified evidence and clinician-entered decisions only." action={<Button icon={RefreshCw} onClick={generate} disabled={busy||!!activeJob}>{activeJob?'Generating…':'Generate draft'}</Button>}/>{error&&<Notice tone="danger">{error}</Notice>}{activeJob&&<Notice>Draft generation is {activeJob.status}. Attempt {activeJob.attempts} of 3; this page will update automatically.</Notice>}{!activeJob&&latestFailedJob&&<Notice tone="danger">Draft generation failed ({latestFailedJob.last_error||'unknown error'}). No report was saved; review the worker log before retrying.</Notice>}<div className="empty"><FileText/><h3>{activeJob?'Draft generation in progress':'No draft generated'}</h3><p>{activeJob?'Bedrock is preparing the evidence-grounded sections.':'Verify source evidence before requesting a draft.'}</p></div></div>;
  const displaySections=draft.sections.map((section,index)=>({section,sourceIndex:index}));
  if(!displaySections.some(item=>item.section.key==='diagnostic_criteria')){const summaryIndex=displaySections.findIndex(item=>item.section.key==='summary');displaySections.splice(summaryIndex<0?displaySections.length:summaryIndex,0,{section:{key:'diagnostic_criteria',heading:'Diagnostic Criteria',paragraphs:[]},sourceIndex:null})}
  return <div><PageTitle eyebrow={`REPORT • VERSION ${draft.version}`} title="Review report" text={`${draft.model_id} · ${draft.prompt_version}`} action={<div className="actions"><Button variant="ghost" icon={RefreshCw} onClick={generate} disabled={busy}>New version</Button>{draft.docx_path&&<a className="button secondary" href={`/api/cases/${data.case.id}/drafts/${draft.id}/docx`}>Download DOCX</a>}</div>}/>{error&&<Notice tone="danger">{error}</Notice>}{draft.warnings.map((w,i)=><Notice key={i}>{w}</Notice>)}
  <div className="report-layout"><div className="report-paper">{displaySections.map(({section,sourceIndex})=>{const isCriteria=section.key==='diagnostic_criteria';return <section key={section.key}><h2>{section.heading}</h2>{isCriteria&&(draft.state==='clinician-approved'&&!draft.input_snapshot?.criteria?<p>The original approved criterion table is preserved in the downloaded report.</p>:<CriteriaReportTable {...reportCriteria(draft,data)}/>)} {section.paragraphs.length?section.paragraphs.map((p,pi)=><div key={`${draft.updated_at}-${pi}`} className={`draft-paragraph ${p.recommendation_group?'recommendation-bullet':''}`}>{p.recommendation_group&&p.recommendation_group!==section.paragraphs[pi-1]?.recommendation_group&&<h3>{recommendationGroups[p.recommendation_group]}</h3>}{p.kind==='clinician_conclusion'&&<h3>Clinician's diagnostic impression</h3>}<div className="paragraph-content">{p.recommendation_group&&<span aria-hidden="true">•</span>}<textarea defaultValue={p.text} rows={Math.max(3,Math.ceil(p.text.length/105))} disabled={draft.state==='clinician-approved'||['clinician_conclusion','intake','missing_information'].includes(p.kind)} onBlur={e=>e.target.value!==p.text&&editParagraph(sourceIndex,pi,e.target.value)}/></div><button onClick={()=>setSelectedEvidence([...(p.evidence_ids||[]),...(p.instrument_ids||[])])}>{(p.evidence_ids||[]).length+(p.instrument_ids||[]).length} sources</button>{p.recommendation_basis&&<small className="recommendation-basis">{p.recommendation_basis==='practical'?'Practical suggestion':p.recommendation_basis==='guideline'?'Guideline-supported option':'Supplied recommendation'} · For clinician review</small>}{p.kind==='intake'&&<small>Details from case intake</small>}</div>):!isCriteria&&<p className="muted">Information not supplied or not yet verified.</p>}</section>})}</div><aside className="evidence-side"><h3>Supporting evidence</h3>{selectedEvidence.length?selectedEvidence.map(id=>{const e=(draft.input_snapshot?.evidence||data.evidence).find(x=>x.id===id),instrument=(draft.input_snapshot?.instruments||data.instruments).find(x=>x.id===id);return e?<blockquote key={id}>“{e.supporting_text}”<small>{e.reporter||'Unknown'} · {e.setting} · {e.source_location}</small></blockquote>:instrument?<blockquote key={id}>{instrument.interpretation}<small>{instrument.instrument} · {instrument.respondent||'Respondent not recorded'}</small><pre>{JSON.stringify(instrument.scores,null,2)}</pre></blockquote>:null}):<p>Select a paragraph’s source count to inspect its evidence.</p>}</aside></div>
  <section className="approval-bar"><label className="check"><input type="checkbox" checked={draft.warnings_acknowledged} disabled={draft.state==='clinician-approved'} onChange={e=>save({warnings_acknowledged:e.target.checked})}/><span>I have reviewed and accept responsibility for unresolved warnings.</span></label><div className="actions">{draft.state==='draft'&&<Button variant="secondary" onClick={()=>save({state:'review-ready'})}>Mark review-ready</Button>}{draft.state==='review-ready'&&<Button icon={Check} onClick={approve}>Approve report</Button>}<span className={`pill ${draft.state}`}>{draft.state}</span></div></section></div>;
}

function App(){const[user,setUser]=useState(null),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{api('/auth/session').then(r=>{csrfToken=r.csrf_token;setUser(r.user)}).catch(()=>{}).finally(()=>setLoading(false))},[]);async function logout(){await api('/auth/logout',{method:'POST',body:'{}'});csrfToken='';setUser(null)}if(loading)return null;if(!user)return <Login onLogin={setUser}/>;return <Shell user={user} onLogout={logout}>{selected?<CaseWorkspace caseId={selected} onBack={()=>setSelected(null)}/>:<CaseList onOpen={setSelected}/>}</Shell>}

createRoot(document.getElementById("root")).render(<App/>);
